### ISSUE TITLE
Create Profile Page

### ISSUE THREAD

**Issue by ankit-mogha** [NashTech-Labs/competency-insights#14]

**Comment by SahilBabbar12** [comment]
1. Working on creating Home page for OKR user profile
2. Completed the project setup with tailwind and created card for user details.
3. Will work on creating okr contributions section.

**Comment by SahilBabbar12** [comment]
![Image](https://github.com/NashTech-Labs/competency-insights/assets/124916680/eafe25c6-a79b-4934-bfe7-b1d54501b7e7)

**Comment by SahilBabbar12** [comment]
implemented Tailwind CSS and made it responsive.
Started creating section for Blog, techub, knolx.
