### ISSUE TITLE
Create Add New OKR Page

### ISSUE THREAD

**Issue by ankit-mogha** [NashTech-Labs/competency-insights#16]

**Comment by Anshika1603** [comment]
1. Created a static page using forms in React.
2. Will study and Implement Tailwind CSS on the same.

**Comment by Anshika1603** [comment]
1. Added Description field.
2. Updated the Submit button and cancel button placement.

![Image](https://github.com/NashTech-Labs/competency-insights/assets/124980025/901229f8-e6fa-4847-9276-5cfea182f0d6)

**Comment by Anshika1603** [comment]
1. Added top Navigation for Add and Update OKR Buttons
2. Increased the width of the form and updated the element alignment.
![image](https://github.com/NashTech-Labs/competency-insights/assets/124980025/45c32cd9-a08f-46a6-9616-7081def5573b)

**Comment by Anshika1603** [comment]
1. Added top Navigation for Switching page between Create OKR and Update OKR.
![image](https://github.com/NashTech-Labs/competency-insights/assets/124980025/2e2902a3-9b74-4acf-8b57-37c0d0a3423e)

![image](https://github.com/NashTech-Labs/competency-insights/assets/124980025/328b9ca0-222d-4cf4-9712-25c623957a58)
