### ISSUE TITLE
Create Update OKR's Page

### ISSUE THREAD

**Issue by ankit-mogha** [NashTech-Labs/competency-insights#17]

**Comment by jasleenwahi** [comment]
1. created a static page.
2. will setup tailwind and do styling for the page

**Comment by jasleenwahi** [comment]
1. did styling to the page.
2. work on completing the page

**Comment by jasleenwahi** [comment]
![Image](https://github.com/NashTech-Labs/competency-insights/assets/124977275/301f55bb-273f-4641-b7dd-fbacf3133057)

**Comment by jasleenwahi** [comment]
1. reworked on creating update okr form- added dropdown for status and activity.
2. added date field for due date and submission date with calender
3. added a field for description.
4. worked on making page responsive.

![Image](https://github.com/NashTech-Labs/competency-insights/assets/124977275/6204f357-5be9-4344-a7c6-82901aac6a95)

**Comment by jasleenwahi** [comment]
1. worked on creating top navbar for the page, to navigate between add okr and update okr page.


![Image](https://github.com/NashTech-Labs/competency-insights/assets/124977275/8876fa2e-4630-40b5-b918-d1b67d82a20c)
