### ISSUE TITLE
Create left bar navigation component

### ISSUE THREAD

**Issue by ankit-mogha** [NashTech-Labs/competency-insights#21]

**Comment by Rahulkrsinhaa** [comment]
create the html and will proceed with the design part

**Comment by Rahulkrsinhaa** [comment]
![Image](https://github.com/NashTech-Labs/competency-insights/assets/124978892/75ebdc1d-addb-4293-a51a-028a5acac34b)

**Comment by Rahulkrsinhaa** [comment]
![Image](https://github.com/NashTech-Labs/competency-insights/assets/124978892/94f8c3cd-1297-4ffe-b047-8ac543491aed)

**Comment by Rahulkrsinhaa** [comment]
1.Changed the icons and added some new icons .
2.changed colors code .
3.used states to hover in and and hover out on menu to open the drop downs 
4.added two of the drop downs in the navbar .

**Comment by Rahulkrsinhaa** [comment]
1. raised pr for nav bar comportment 
https://github.com/NashTech-Labs/competency-insights/pull/40

**Comment by Rahulkrsinhaa** [comment]
![Image](https://github.com/NashTech-Labs/competency-insights/assets/124978892/cf4a1b69-7725-4549-b215-3654297cd59e)
