### ISSUE TITLE
Create Teams Details Page

### ISSUE THREAD

**Issue by ankit-mogha** [NashTech-Labs/competency-insights#27]

**Comment by riyaknol11** [comment]
1. Working on making a static web-page for the reporting members of a team.
2. Completed the set-up and made  flip cards for each member of the team
3. Looking for ui ideas for the page.

**Comment by riyaknol11** [comment]
![Image](https://github.com/NashTech-Labs/competency-insights/assets/124979006/036badeb-4055-4378-b80e-845670bf5fc5)

**Comment by riyaknol11** [comment]
> ![Image](https://private-user-images.githubusercontent.com/124979006/309659526-036badeb-4055-4378-b80e-845670bf5fc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzU5NjMsIm5iZiI6MTcwOTUzNTY2MywicGF0aCI6Ii8xMjQ5NzkwMDYvMzA5NjU5NTI2LTAzNmJhZGViLTQwNTUtNDM3OC1iODBlLTg0NTY3MGJmNWZjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwNzAxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTMxMzc4NzcxZmYwNDMzOTgzNGM4ZDFlZTc4YzNlMjVmYTg5ZTgxZmZhOTdlM2E4OTNlY2I0OWJhMmRjMDA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HpImsFvFhTGnPkLZBSsHwd-KxC4qc7x8KDQQMIG9Rr4)

**Comment by riyaknol11** [comment]
1. Added the button to navigate to the profile of the reporting member
2. Changed the css of the cards.
3. Started working on the frame that will appear for the 'tasks to review'



![Image](https://github.com/NashTech-Labs/competency-insights/assets/124979006/90dd8227-719d-4fab-baa2-82d6185e771b)

**Comment by riyaknol11** [comment]
1. Changed the color palette of the page. 



![Image](https://github.com/NashTech-Labs/competency-insights/assets/124979006/df68da61-13d8-48a4-89fc-6007a780e695)



![Image](https://github.com/NashTech-Labs/competency-insights/assets/124979006/c463332b-73dc-4edb-bbae-f33841298f84)
